name = "serverless-hit-counter"
main = "./index.js"
compatibility_date = "2024-04-25"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
    { binding = "kv", id = "68c44ae520a74cf293114439baaa1f94" }
]
routes = [
        { pattern = "hits.s0.rs", custom_domain = true }
]
